package project.vilsoncake.common.models;

public enum CallbackType {
  CHANGE_AIRPORT,
  CHANGE_BOT_MODE,
  DEFAULT_BOT_MODE_SELECTED,
  ONLY_SCHEDULED_FLIGHTS_BOT_MODE_SELECTED,
  ONLY_SPECIFIC_AIRCRAFT_BOT_MODE_SELECTED,
  MUTE_BOT_MODE_SELECTED
}
