spring:
  application:
    name: bot-commands-processing-lambda
  main:
    web-application-type: none
  cloud:
    function:
      definition: botCommandsHandler

bot:
  token: ${BOT_TOKEN}
  telegram-api-url-template: 'https://api.telegram.org/bot%s/sendMessage'