spring:
  application:
    name: bot-commands-processing-lambda
  main:
    web-application-type: none
  cloud:
    function:
      definition: botCommandsHandler
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

bot:
  token: ${BOT_TOKEN}
  telegram-api-url: https://api.telegram.org/bot${BOT_TOKEN}/sendMessage

general:
  timezone: Europe/Warsaw