package project.vilsoncake.flightsnotificationlambda.models;

public enum MessageType {
  SINGLE_SCHEDULED_FLIGHT_TITLE,
  SCHEDULED_FLIGHTS_TITLE,
  SINGE_SCHEDULED_FLIGHT_DETAILS,
  PLURAL_SCHEDULED_FLIGHT_DETAILS,
  FLIGHT_LIVE_NOTIFICATION,
  FLIGHT_LIVE_NOTIFICATION_DETAILS,
  FLIGHT_DELAYED_NOTIFICATION,
  FLIGHT_DELAYED_NOTIFICATION_DETAILS,
  FLIGHT_CANCELLED_NOTIFICATION,
  FLIGHT_CANCELLED_NOTIFICATION_DETAILS,
  FLIGHT_ETA_DELAYED_NOTIFICATION,
  FLIGHT_ETA_EARLIER_NOTIFICATION,
  FLIGHT_ETA_CHANGED_NOTIFICATION_DETAILS,
  FLIGHT_ARRIVING_SOON_NOTIFICATION,
  FLIGHT_ARRIVING_SOON_NOTIFICATION_DETAILS
}
