name: Deploy flightradar-api-lambdas

on:
  push:
    branches:
      - main
    paths:
      - 'flightradar-api-lambdas/**'
      - '.github/workflows/deploy-flightradar-api-lambdas.yml'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd flightradar-api-lambdas
          pip install -r requirements.txt -t package/
          cp -r utils models static package/

      - name: Zip Lambdas Sources
        run: |
          cd flightradar-api-lambdas
          cp get_airport_lambda.py package/ && cd package && zip -r ../get_airport_lambda.zip . && cd ..
          cp get_scheduled_flights_lambda.py package/ && cd package && zip -r ../get_scheduled_flights_lambda.zip . && cd ..
          cp get_specific_aircraft_lambda.py package/ && cd package && zip -r ../get_specific_aircraft_lambda.zip . && cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambdas
        run: |
          aws lambda update-function-code \
            --function-name aviation-telegram-bot-flightradar-api-get-airport \
            --zip-file fileb://flightradar-api-lambdas/get_airport_lambda.zip
          
          aws lambda update-function-code \
            --function-name aviation-telegram-bot-flightradar-api-get-scheduled-flights \
            --zip-file fileb://flightradar-api-lambdas/get_scheduled_flights_lambda.zip
          
          aws lambda update-function-code \
            --function-name aviation-telegram-bot-flightradar-api-get-specific-aircraft \
            --zip-file fileb://flightradar-api-lambdas/get_specific_aircraft_lambda.zip
