name: Deploy flightradar-api-lambdas

on:
  push:
    branches:
      - main
    paths:
      - 'flightradar-api-lambdas/**'
      - '.github/workflows/deploy-flightradar-api-lambdas.yml'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip Lambdas Sources
        run: |
          cd flightradar-api-lambdas
          zip get_airport_lambda.zip get_airport_lambda.py
          zip get_scheduled_flights_lambda.zip get_scheduled_flights_lambda.py
          zip get_specific_aircraft_lambda.zip get_specific_aircraft_lambda.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambdas
        run: |
          aws lambda update-function-code \
            --function-name aviation-telegram-bot-flightradar-api-get-airport \
            --zip-file fileb://flightradar-api-lambdas/get_airport_lambda.zip
          
          aws lambda update-function-code \
            --function-name aviation-telegram-bot-flightradar-api-get-scheduled-flights \
            --zip-file fileb://flightradar-api-lambdas/get_scheduled_flights_lambda.zip
          
          aws lambda update-function-code \
            --function-name aviation-telegram-bot-flightradar-api-get-specific-aircraft \
            --zip-file fileb://flightradar-api-lambdas/get_specific_aircraft_lambda.zip
